### ISSUE TITLE
Show how to encode messages to support IoT Hub Routing Queries

### ISSUE THREAD

**Issue by Teodelas** [Azure-Samples/azure-iot-samples-csharp#68]
Can you show how to encode messages as UTF-8, UTF-16, or UTF-32 so that IoT Hub Routing Queries work against the message body?

**Comment by robinsh** [comment]
#please-close 
I did not add the encoding to the quickstart referenced by @Teodelas. I added it to the c# tutorial for message routing because it turned out to be fairly complicated, and I wanted there to be a sample they could run (as you can run the tutorial) and see the encoded message bodies. I also included code to decode the message body from UTF-32 back to ASCII.
Article originally marked as an issue:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-routing-query-syntax
IoT C# Samples: 
https://github.com/Azure-Samples/azure-iot-samples-csharp/
